include:
 - 'https://source.puri.sm/Librem5/librem5-ci/raw/master/librem5-pipeline-definitions.yml'
 - 'https://source.puri.sm/Librem5/librem5-ci/raw/master/librem5-pipeline-byzantium-jobs.yml'

stages:
 - build
 - test
 - package
 - test-package

build:native:
  stage: build
  artifacts:
    paths:
      - _build
  variables:
    COMMON_BUILD_OPTS: -Db_coverage=true --werror
    BUILD_OPTS: -Dgtk_doc=true ${COMMON_BUILD_OPTS}
    WANT_BUILD_DEPS: "true"
  except:
    variables:
      - $PKG_ONLY == "1"
  image: pureos/byzantium
  tags:
    - librem5
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -y update
    - apt-get -y install lcov
    - apt-get -y build-dep .
    - ulimit -c unlimited
  script:
    - 'echo "Build opts: ${BUILD_OPTS}"'
    - meson ${BUILD_OPTS} . _build
    - ninja -C _build

test:native:
  extends: build:native
  stage: test
  dependencies:
    - build:native
  script:
    - export LC_ALL=C.UTF-8
    - xvfb-run -s -noreset ninja -C _build test
    - cp _build/src/libcalls-vala.a.p/*.c _build
    - ninja -C _build coverage
  coverage: '/^\s+lines\.+:\s+([\d.]+\%)\s+/'

build-gtkdoc:
  extends: build:native
  stage: test
  dependencies:
    - build:native
  script:
    - ninja -C _build calls-doc
    - mv _build/doc/html/ _reference/
  artifacts:
    paths:
      - _reference

check-po:
  extends: build:native
  stage: test
  dependencies:
    - build:native
  before_script:
    - apt-get -y update
    - apt-get -y install intltool
  script:
    # barf on untranslated C files. Seems intltool
    # can't be told to exit with non-zero exit status
    # in this case
    - cd po/
    - intltool-update -m 2>&1 | grep -qs '/.*\.c' && { intltool-update -m; exit 1; } || exit 0
